/*
 * Generated by gdbus-codegen 2.56.2. DO NOT EDIT.
 *
 * The license of this code is the same as for the D-Bus interface description
 * it was derived from.
 */

#ifdef HAVE_CONFIG_H
#  include "config.h"
#endif

#include "group-generated.h"

#include <string.h>
#ifdef G_OS_UNIX
#  include <gio/gunixfdlist.h>
#endif

typedef struct
{
  GDBusArgInfo parent_struct;
  gboolean use_gvariant;
} _ExtendedGDBusArgInfo;

typedef struct
{
  GDBusMethodInfo parent_struct;
  const gchar *signal_name;
  gboolean pass_fdlist;
} _ExtendedGDBusMethodInfo;

typedef struct
{
  GDBusSignalInfo parent_struct;
  const gchar *signal_name;
} _ExtendedGDBusSignalInfo;

typedef struct
{
  GDBusPropertyInfo parent_struct;
  const gchar *hyphen_name;
  gboolean use_gvariant;
} _ExtendedGDBusPropertyInfo;

typedef struct
{
  GDBusInterfaceInfo parent_struct;
  const gchar *hyphen_name;
} _ExtendedGDBusInterfaceInfo;

typedef struct
{
  const _ExtendedGDBusPropertyInfo *info;
  guint prop_id;
  GValue orig_value; /* the value before the change */
} ChangedProperty;

static void
_changed_property_free (ChangedProperty *data)
{
  g_value_unset (&data->orig_value);
  g_free (data);
}

static gboolean
_g_strv_equal0 (gchar **a, gchar **b)
{
  gboolean ret = FALSE;
  guint n;
  if (a == NULL && b == NULL)
    {
      ret = TRUE;
      goto out;
    }
  if (a == NULL || b == NULL)
    goto out;
  if (g_strv_length (a) != g_strv_length (b))
    goto out;
  for (n = 0; a[n] != NULL; n++)
    if (g_strcmp0 (a[n], b[n]) != 0)
      goto out;
  ret = TRUE;
out:
  return ret;
}

static gboolean
_g_variant_equal0 (GVariant *a, GVariant *b)
{
  gboolean ret = FALSE;
  if (a == NULL && b == NULL)
    {
      ret = TRUE;
      goto out;
    }
  if (a == NULL || b == NULL)
    goto out;
  ret = g_variant_equal (a, b);
out:
  return ret;
}

G_GNUC_UNUSED static gboolean
_g_value_equal (const GValue *a, const GValue *b)
{
  gboolean ret = FALSE;
  g_assert (G_VALUE_TYPE (a) == G_VALUE_TYPE (b));
  switch (G_VALUE_TYPE (a))
    {
      case G_TYPE_BOOLEAN:
        ret = (g_value_get_boolean (a) == g_value_get_boolean (b));
        break;
      case G_TYPE_UCHAR:
        ret = (g_value_get_uchar (a) == g_value_get_uchar (b));
        break;
      case G_TYPE_INT:
        ret = (g_value_get_int (a) == g_value_get_int (b));
        break;
      case G_TYPE_UINT:
        ret = (g_value_get_uint (a) == g_value_get_uint (b));
        break;
      case G_TYPE_INT64:
        ret = (g_value_get_int64 (a) == g_value_get_int64 (b));
        break;
      case G_TYPE_UINT64:
        ret = (g_value_get_uint64 (a) == g_value_get_uint64 (b));
        break;
      case G_TYPE_DOUBLE:
        {
          /* Avoid -Wfloat-equal warnings by doing a direct bit compare */
          gdouble da = g_value_get_double (a);
          gdouble db = g_value_get_double (b);
          ret = memcmp (&da, &db, sizeof (gdouble)) == 0;
        }
        break;
      case G_TYPE_STRING:
        ret = (g_strcmp0 (g_value_get_string (a), g_value_get_string (b)) == 0);
        break;
      case G_TYPE_VARIANT:
        ret = _g_variant_equal0 (g_value_get_variant (a), g_value_get_variant (b));
        break;
      default:
        if (G_VALUE_TYPE (a) == G_TYPE_STRV)
          ret = _g_strv_equal0 (g_value_get_boxed (a), g_value_get_boxed (b));
        else
          g_critical ("_g_value_equal() does not handle type %s", g_type_name (G_VALUE_TYPE (a)));
        break;
    }
  return ret;
}

/* ------------------------------------------------------------------------
 * Code for interface org.group.admin
 * ------------------------------------------------------------------------
 */

/**
 * SECTION:groupAdmin
 * @title: groupAdmin
 * @short_description: Generated C code for the org.group.admin D-Bus interface
 *
 * This section contains code for working with the <link linkend="gdbus-interface-org-group-admin.top_of_page">org.group.admin</link> D-Bus interface in C.
 */

/* ---- Introspection data for org.group.admin ---- */

static const _ExtendedGDBusArgInfo _group_admin_method_info_find_group_by_id_IN_ARG_id =
{
  {
    -1,
    (gchar *) "id",
    (gchar *) "x",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _group_admin_method_info_find_group_by_id_IN_ARG_pointers[] =
{
  &_group_admin_method_info_find_group_by_id_IN_ARG_id,
  NULL
};

static const _ExtendedGDBusArgInfo _group_admin_method_info_find_group_by_id_OUT_ARG_group =
{
  {
    -1,
    (gchar *) "group",
    (gchar *) "o",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _group_admin_method_info_find_group_by_id_OUT_ARG_pointers[] =
{
  &_group_admin_method_info_find_group_by_id_OUT_ARG_group,
  NULL
};

static const _ExtendedGDBusMethodInfo _group_admin_method_info_find_group_by_id =
{
  {
    -1,
    (gchar *) "FindGroupById",
    (GDBusArgInfo **) &_group_admin_method_info_find_group_by_id_IN_ARG_pointers,
    (GDBusArgInfo **) &_group_admin_method_info_find_group_by_id_OUT_ARG_pointers,
    NULL
  },
  "handle-find-group-by-id",
  FALSE
};

static const _ExtendedGDBusArgInfo _group_admin_method_info_find_group_by_name_IN_ARG_name =
{
  {
    -1,
    (gchar *) "name",
    (gchar *) "s",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _group_admin_method_info_find_group_by_name_IN_ARG_pointers[] =
{
  &_group_admin_method_info_find_group_by_name_IN_ARG_name,
  NULL
};

static const _ExtendedGDBusArgInfo _group_admin_method_info_find_group_by_name_OUT_ARG_group =
{
  {
    -1,
    (gchar *) "group",
    (gchar *) "o",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _group_admin_method_info_find_group_by_name_OUT_ARG_pointers[] =
{
  &_group_admin_method_info_find_group_by_name_OUT_ARG_group,
  NULL
};

static const _ExtendedGDBusMethodInfo _group_admin_method_info_find_group_by_name =
{
  {
    -1,
    (gchar *) "FindGroupByName",
    (GDBusArgInfo **) &_group_admin_method_info_find_group_by_name_IN_ARG_pointers,
    (GDBusArgInfo **) &_group_admin_method_info_find_group_by_name_OUT_ARG_pointers,
    NULL
  },
  "handle-find-group-by-name",
  FALSE
};

static const _ExtendedGDBusArgInfo _group_admin_method_info_create_group_IN_ARG_name =
{
  {
    -1,
    (gchar *) "name",
    (gchar *) "s",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _group_admin_method_info_create_group_IN_ARG_pointers[] =
{
  &_group_admin_method_info_create_group_IN_ARG_name,
  NULL
};

static const _ExtendedGDBusArgInfo _group_admin_method_info_create_group_OUT_ARG_group =
{
  {
    -1,
    (gchar *) "group",
    (gchar *) "o",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _group_admin_method_info_create_group_OUT_ARG_pointers[] =
{
  &_group_admin_method_info_create_group_OUT_ARG_group,
  NULL
};

static const _ExtendedGDBusMethodInfo _group_admin_method_info_create_group =
{
  {
    -1,
    (gchar *) "CreateGroup",
    (GDBusArgInfo **) &_group_admin_method_info_create_group_IN_ARG_pointers,
    (GDBusArgInfo **) &_group_admin_method_info_create_group_OUT_ARG_pointers,
    NULL
  },
  "handle-create-group",
  FALSE
};

static const _ExtendedGDBusArgInfo _group_admin_method_info_delete_group_IN_ARG_id =
{
  {
    -1,
    (gchar *) "id",
    (gchar *) "x",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _group_admin_method_info_delete_group_IN_ARG_pointers[] =
{
  &_group_admin_method_info_delete_group_IN_ARG_id,
  NULL
};

static const _ExtendedGDBusMethodInfo _group_admin_method_info_delete_group =
{
  {
    -1,
    (gchar *) "DeleteGroup",
    (GDBusArgInfo **) &_group_admin_method_info_delete_group_IN_ARG_pointers,
    NULL,
    NULL
  },
  "handle-delete-group",
  FALSE
};

static const _ExtendedGDBusMethodInfo * const _group_admin_method_info_pointers[] =
{
  &_group_admin_method_info_find_group_by_id,
  &_group_admin_method_info_find_group_by_name,
  &_group_admin_method_info_create_group,
  &_group_admin_method_info_delete_group,
  NULL
};

static const _ExtendedGDBusArgInfo _group_admin_signal_info_group_added_ARG_user =
{
  {
    -1,
    (gchar *) "user",
    (gchar *) "o",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _group_admin_signal_info_group_added_ARG_pointers[] =
{
  &_group_admin_signal_info_group_added_ARG_user,
  NULL
};

static const _ExtendedGDBusSignalInfo _group_admin_signal_info_group_added =
{
  {
    -1,
    (gchar *) "GroupAdded",
    (GDBusArgInfo **) &_group_admin_signal_info_group_added_ARG_pointers,
    NULL
  },
  "group-added"
};

static const _ExtendedGDBusArgInfo _group_admin_signal_info_group_deleted_ARG_user =
{
  {
    -1,
    (gchar *) "user",
    (gchar *) "o",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _group_admin_signal_info_group_deleted_ARG_pointers[] =
{
  &_group_admin_signal_info_group_deleted_ARG_user,
  NULL
};

static const _ExtendedGDBusSignalInfo _group_admin_signal_info_group_deleted =
{
  {
    -1,
    (gchar *) "GroupDeleted",
    (GDBusArgInfo **) &_group_admin_signal_info_group_deleted_ARG_pointers,
    NULL
  },
  "group-deleted"
};

static const _ExtendedGDBusSignalInfo * const _group_admin_signal_info_pointers[] =
{
  &_group_admin_signal_info_group_added,
  &_group_admin_signal_info_group_deleted,
  NULL
};

static const _ExtendedGDBusPropertyInfo _group_admin_property_info_version =
{
  {
    -1,
    (gchar *) "Version",
    (gchar *) "s",
    G_DBUS_PROPERTY_INFO_FLAGS_READABLE,
    NULL
  },
  "version",
  FALSE
};

static const _ExtendedGDBusPropertyInfo * const _group_admin_property_info_pointers[] =
{
  &_group_admin_property_info_version,
  NULL
};

static const _ExtendedGDBusInterfaceInfo _group_admin_interface_info =
{
  {
    -1,
    (gchar *) "org.group.admin",
    (GDBusMethodInfo **) &_group_admin_method_info_pointers,
    (GDBusSignalInfo **) &_group_admin_signal_info_pointers,
    (GDBusPropertyInfo **) &_group_admin_property_info_pointers,
    NULL
  },
  "admin",
};


/**
 * group_admin_interface_info:
 *
 * Gets a machine-readable description of the <link linkend="gdbus-interface-org-group-admin.top_of_page">org.group.admin</link> D-Bus interface.
 *
 * Returns: (transfer none): A #GDBusInterfaceInfo. Do not free.
 */
GDBusInterfaceInfo *
group_admin_interface_info (void)
{
  return (GDBusInterfaceInfo *) &_group_admin_interface_info.parent_struct;
}

/**
 * group_admin_override_properties:
 * @klass: The class structure for a #GObject derived class.
 * @property_id_begin: The property id to assign to the first overridden property.
 *
 * Overrides all #GObject properties in the #groupAdmin interface for a concrete class.
 * The properties are overridden in the order they are defined.
 *
 * Returns: The last property id.
 */
guint
group_admin_override_properties (GObjectClass *klass, guint property_id_begin)
{
  g_object_class_override_property (klass, property_id_begin++, "version");
  return property_id_begin - 1;
}



/**
 * groupAdmin:
 *
 * Abstract interface type for the D-Bus interface <link linkend="gdbus-interface-org-group-admin.top_of_page">org.group.admin</link>.
 */

/**
 * groupAdminIface:
 * @parent_iface: The parent interface.
 * @handle_create_group: Handler for the #groupAdmin::handle-create-group signal.
 * @handle_delete_group: Handler for the #groupAdmin::handle-delete-group signal.
 * @handle_find_group_by_id: Handler for the #groupAdmin::handle-find-group-by-id signal.
 * @handle_find_group_by_name: Handler for the #groupAdmin::handle-find-group-by-name signal.
 * @get_version: Getter for the #groupAdmin:version property.
 * @group_added: Handler for the #groupAdmin::group-added signal.
 * @group_deleted: Handler for the #groupAdmin::group-deleted signal.
 *
 * Virtual table for the D-Bus interface <link linkend="gdbus-interface-org-group-admin.top_of_page">org.group.admin</link>.
 */

typedef groupAdminIface groupAdminInterface;
G_DEFINE_INTERFACE (groupAdmin, group_admin, G_TYPE_OBJECT)

static void
group_admin_default_init (groupAdminIface *iface)
{
  /* GObject signals for incoming D-Bus method calls: */
  /**
   * groupAdmin::handle-find-group-by-id:
   * @object: A #groupAdmin.
   * @invocation: A #GDBusMethodInvocation.
   * @arg_id: Argument passed by remote caller.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-org-group-admin.FindGroupById">FindGroupById()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call group_admin_complete_find_group_by_id() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-find-group-by-id",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (groupAdminIface, handle_find_group_by_id),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    2,
    G_TYPE_DBUS_METHOD_INVOCATION, G_TYPE_INT64);

  /**
   * groupAdmin::handle-find-group-by-name:
   * @object: A #groupAdmin.
   * @invocation: A #GDBusMethodInvocation.
   * @arg_name: Argument passed by remote caller.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-org-group-admin.FindGroupByName">FindGroupByName()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call group_admin_complete_find_group_by_name() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-find-group-by-name",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (groupAdminIface, handle_find_group_by_name),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    2,
    G_TYPE_DBUS_METHOD_INVOCATION, G_TYPE_STRING);

  /**
   * groupAdmin::handle-create-group:
   * @object: A #groupAdmin.
   * @invocation: A #GDBusMethodInvocation.
   * @arg_name: Argument passed by remote caller.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-org-group-admin.CreateGroup">CreateGroup()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call group_admin_complete_create_group() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-create-group",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (groupAdminIface, handle_create_group),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    2,
    G_TYPE_DBUS_METHOD_INVOCATION, G_TYPE_STRING);

  /**
   * groupAdmin::handle-delete-group:
   * @object: A #groupAdmin.
   * @invocation: A #GDBusMethodInvocation.
   * @arg_id: Argument passed by remote caller.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-org-group-admin.DeleteGroup">DeleteGroup()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call group_admin_complete_delete_group() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-delete-group",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (groupAdminIface, handle_delete_group),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    2,
    G_TYPE_DBUS_METHOD_INVOCATION, G_TYPE_INT64);

  /* GObject signals for received D-Bus signals: */
  /**
   * groupAdmin::group-added:
   * @object: A #groupAdmin.
   * @arg_user: Argument.
   *
   * On the client-side, this signal is emitted whenever the D-Bus signal <link linkend="gdbus-signal-org-group-admin.GroupAdded">"GroupAdded"</link> is received.
   *
   * On the service-side, this signal can be used with e.g. g_signal_emit_by_name() to make the object emit the D-Bus signal.
   */
  g_signal_new ("group-added",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (groupAdminIface, group_added),
    NULL,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_NONE,
    1, G_TYPE_STRING);

  /**
   * groupAdmin::group-deleted:
   * @object: A #groupAdmin.
   * @arg_user: Argument.
   *
   * On the client-side, this signal is emitted whenever the D-Bus signal <link linkend="gdbus-signal-org-group-admin.GroupDeleted">"GroupDeleted"</link> is received.
   *
   * On the service-side, this signal can be used with e.g. g_signal_emit_by_name() to make the object emit the D-Bus signal.
   */
  g_signal_new ("group-deleted",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (groupAdminIface, group_deleted),
    NULL,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_NONE,
    1, G_TYPE_STRING);

  /* GObject properties for D-Bus properties: */
  /**
   * groupAdmin:version:
   *
   * Represents the D-Bus property <link linkend="gdbus-property-org-group-admin.Version">"Version"</link>.
   *
   * Since the D-Bus property for this #GObject property is readable but not writable, it is meaningful to read from it on both the client- and service-side. It is only meaningful, however, to write to it on the service-side.
   */
  g_object_interface_install_property (iface,
    g_param_spec_string ("version", "Version", "Version", NULL, G_PARAM_READWRITE | G_PARAM_STATIC_STRINGS));
}

/**
 * group_admin_get_version: (skip)
 * @object: A #groupAdmin.
 *
 * Gets the value of the <link linkend="gdbus-property-org-group-admin.Version">"Version"</link> D-Bus property.
 *
 * Since this D-Bus property is readable, it is meaningful to use this function on both the client- and service-side.
 *
 * <warning>The returned value is only valid until the property changes so on the client-side it is only safe to use this function on the thread where @object was constructed. Use group_admin_dup_version() if on another thread.</warning>
 *
 * Returns: (transfer none): The property value or %NULL if the property is not set. Do not free the returned value, it belongs to @object.
 */
const gchar *
group_admin_get_version (groupAdmin *object)
{
  return GROUP_ADMIN_GET_IFACE (object)->get_version (object);
}

/**
 * group_admin_dup_version: (skip)
 * @object: A #groupAdmin.
 *
 * Gets a copy of the <link linkend="gdbus-property-org-group-admin.Version">"Version"</link> D-Bus property.
 *
 * Since this D-Bus property is readable, it is meaningful to use this function on both the client- and service-side.
 *
 * Returns: (transfer full): The property value or %NULL if the property is not set. The returned value should be freed with g_free().
 */
gchar *
group_admin_dup_version (groupAdmin *object)
{
  gchar *value;
  g_object_get (G_OBJECT (object), "version", &value, NULL);
  return value;
}

/**
 * group_admin_set_version: (skip)
 * @object: A #groupAdmin.
 * @value: The value to set.
 *
 * Sets the <link linkend="gdbus-property-org-group-admin.Version">"Version"</link> D-Bus property to @value.
 *
 * Since this D-Bus property is not writable, it is only meaningful to use this function on the service-side.
 */
void
group_admin_set_version (groupAdmin *object, const gchar *value)
{
  g_object_set (G_OBJECT (object), "version", value, NULL);
}

/**
 * group_admin_emit_group_added:
 * @object: A #groupAdmin.
 * @arg_user: Argument to pass with the signal.
 *
 * Emits the <link linkend="gdbus-signal-org-group-admin.GroupAdded">"GroupAdded"</link> D-Bus signal.
 */
void
group_admin_emit_group_added (
    groupAdmin *object,
    const gchar *arg_user)
{
  g_signal_emit_by_name (object, "group-added", arg_user);
}

/**
 * group_admin_emit_group_deleted:
 * @object: A #groupAdmin.
 * @arg_user: Argument to pass with the signal.
 *
 * Emits the <link linkend="gdbus-signal-org-group-admin.GroupDeleted">"GroupDeleted"</link> D-Bus signal.
 */
void
group_admin_emit_group_deleted (
    groupAdmin *object,
    const gchar *arg_user)
{
  g_signal_emit_by_name (object, "group-deleted", arg_user);
}

/**
 * group_admin_call_find_group_by_id:
 * @proxy: A #groupAdminProxy.
 * @arg_id: Argument to pass with the method invocation.
 * @cancellable: (nullable): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-org-group-admin.FindGroupById">FindGroupById()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call group_admin_call_find_group_by_id_finish() to get the result of the operation.
 *
 * See group_admin_call_find_group_by_id_sync() for the synchronous, blocking version of this method.
 */
void
group_admin_call_find_group_by_id (
    groupAdmin *proxy,
    gint64 arg_id,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "FindGroupById",
    g_variant_new ("(x)",
                   arg_id),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * group_admin_call_find_group_by_id_finish:
 * @proxy: A #groupAdminProxy.
 * @out_group: (out): Return location for return parameter or %NULL to ignore.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to group_admin_call_find_group_by_id().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with group_admin_call_find_group_by_id().
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
group_admin_call_find_group_by_id_finish (
    groupAdmin *proxy,
    gchar **out_group,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(o)",
                 out_group);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * group_admin_call_find_group_by_id_sync:
 * @proxy: A #groupAdminProxy.
 * @arg_id: Argument to pass with the method invocation.
 * @out_group: (out): Return location for return parameter or %NULL to ignore.
 * @cancellable: (nullable): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-org-group-admin.FindGroupById">FindGroupById()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See group_admin_call_find_group_by_id() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
group_admin_call_find_group_by_id_sync (
    groupAdmin *proxy,
    gint64 arg_id,
    gchar **out_group,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "FindGroupById",
    g_variant_new ("(x)",
                   arg_id),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(o)",
                 out_group);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * group_admin_call_find_group_by_name:
 * @proxy: A #groupAdminProxy.
 * @arg_name: Argument to pass with the method invocation.
 * @cancellable: (nullable): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-org-group-admin.FindGroupByName">FindGroupByName()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call group_admin_call_find_group_by_name_finish() to get the result of the operation.
 *
 * See group_admin_call_find_group_by_name_sync() for the synchronous, blocking version of this method.
 */
void
group_admin_call_find_group_by_name (
    groupAdmin *proxy,
    const gchar *arg_name,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "FindGroupByName",
    g_variant_new ("(s)",
                   arg_name),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * group_admin_call_find_group_by_name_finish:
 * @proxy: A #groupAdminProxy.
 * @out_group: (out): Return location for return parameter or %NULL to ignore.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to group_admin_call_find_group_by_name().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with group_admin_call_find_group_by_name().
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
group_admin_call_find_group_by_name_finish (
    groupAdmin *proxy,
    gchar **out_group,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(o)",
                 out_group);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * group_admin_call_find_group_by_name_sync:
 * @proxy: A #groupAdminProxy.
 * @arg_name: Argument to pass with the method invocation.
 * @out_group: (out): Return location for return parameter or %NULL to ignore.
 * @cancellable: (nullable): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-org-group-admin.FindGroupByName">FindGroupByName()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See group_admin_call_find_group_by_name() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
group_admin_call_find_group_by_name_sync (
    groupAdmin *proxy,
    const gchar *arg_name,
    gchar **out_group,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "FindGroupByName",
    g_variant_new ("(s)",
                   arg_name),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(o)",
                 out_group);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * group_admin_call_create_group:
 * @proxy: A #groupAdminProxy.
 * @arg_name: Argument to pass with the method invocation.
 * @cancellable: (nullable): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-org-group-admin.CreateGroup">CreateGroup()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call group_admin_call_create_group_finish() to get the result of the operation.
 *
 * See group_admin_call_create_group_sync() for the synchronous, blocking version of this method.
 */
void
group_admin_call_create_group (
    groupAdmin *proxy,
    const gchar *arg_name,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "CreateGroup",
    g_variant_new ("(s)",
                   arg_name),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * group_admin_call_create_group_finish:
 * @proxy: A #groupAdminProxy.
 * @out_group: (out): Return location for return parameter or %NULL to ignore.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to group_admin_call_create_group().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with group_admin_call_create_group().
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
group_admin_call_create_group_finish (
    groupAdmin *proxy,
    gchar **out_group,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(o)",
                 out_group);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * group_admin_call_create_group_sync:
 * @proxy: A #groupAdminProxy.
 * @arg_name: Argument to pass with the method invocation.
 * @out_group: (out): Return location for return parameter or %NULL to ignore.
 * @cancellable: (nullable): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-org-group-admin.CreateGroup">CreateGroup()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See group_admin_call_create_group() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
group_admin_call_create_group_sync (
    groupAdmin *proxy,
    const gchar *arg_name,
    gchar **out_group,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "CreateGroup",
    g_variant_new ("(s)",
                   arg_name),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(o)",
                 out_group);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * group_admin_call_delete_group:
 * @proxy: A #groupAdminProxy.
 * @arg_id: Argument to pass with the method invocation.
 * @cancellable: (nullable): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-org-group-admin.DeleteGroup">DeleteGroup()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call group_admin_call_delete_group_finish() to get the result of the operation.
 *
 * See group_admin_call_delete_group_sync() for the synchronous, blocking version of this method.
 */
void
group_admin_call_delete_group (
    groupAdmin *proxy,
    gint64 arg_id,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "DeleteGroup",
    g_variant_new ("(x)",
                   arg_id),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * group_admin_call_delete_group_finish:
 * @proxy: A #groupAdminProxy.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to group_admin_call_delete_group().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with group_admin_call_delete_group().
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
group_admin_call_delete_group_finish (
    groupAdmin *proxy,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * group_admin_call_delete_group_sync:
 * @proxy: A #groupAdminProxy.
 * @arg_id: Argument to pass with the method invocation.
 * @cancellable: (nullable): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-org-group-admin.DeleteGroup">DeleteGroup()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See group_admin_call_delete_group() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
group_admin_call_delete_group_sync (
    groupAdmin *proxy,
    gint64 arg_id,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "DeleteGroup",
    g_variant_new ("(x)",
                   arg_id),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * group_admin_complete_find_group_by_id:
 * @object: A #groupAdmin.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 * @group: Parameter to return.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-org-group-admin.FindGroupById">FindGroupById()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
group_admin_complete_find_group_by_id (
    groupAdmin *object,
    GDBusMethodInvocation *invocation,
    const gchar *group)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("(o)",
                   group));
}

/**
 * group_admin_complete_find_group_by_name:
 * @object: A #groupAdmin.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 * @group: Parameter to return.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-org-group-admin.FindGroupByName">FindGroupByName()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
group_admin_complete_find_group_by_name (
    groupAdmin *object,
    GDBusMethodInvocation *invocation,
    const gchar *group)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("(o)",
                   group));
}

/**
 * group_admin_complete_create_group:
 * @object: A #groupAdmin.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 * @group: Parameter to return.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-org-group-admin.CreateGroup">CreateGroup()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
group_admin_complete_create_group (
    groupAdmin *object,
    GDBusMethodInvocation *invocation,
    const gchar *group)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("(o)",
                   group));
}

/**
 * group_admin_complete_delete_group:
 * @object: A #groupAdmin.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-org-group-admin.DeleteGroup">DeleteGroup()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
group_admin_complete_delete_group (
    groupAdmin *object,
    GDBusMethodInvocation *invocation)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("()"));
}

/* ------------------------------------------------------------------------ */

/**
 * groupAdminProxy:
 *
 * The #groupAdminProxy structure contains only private data and should only be accessed using the provided API.
 */

/**
 * groupAdminProxyClass:
 * @parent_class: The parent class.
 *
 * Class structure for #groupAdminProxy.
 */

struct _groupAdminProxyPrivate
{
  GData *qdata;
};

static void group_admin_proxy_iface_init (groupAdminIface *iface);

#if GLIB_VERSION_MAX_ALLOWED >= GLIB_VERSION_2_38
G_DEFINE_TYPE_WITH_CODE (groupAdminProxy, group_admin_proxy, G_TYPE_DBUS_PROXY,
                         G_ADD_PRIVATE (groupAdminProxy)
                         G_IMPLEMENT_INTERFACE (GROUP_TYPE_ADMIN, group_admin_proxy_iface_init))

#else
G_DEFINE_TYPE_WITH_CODE (groupAdminProxy, group_admin_proxy, G_TYPE_DBUS_PROXY,
                         G_IMPLEMENT_INTERFACE (GROUP_TYPE_ADMIN, group_admin_proxy_iface_init))

#endif
static void
group_admin_proxy_finalize (GObject *object)
{
  groupAdminProxy *proxy = GROUP_ADMIN_PROXY (object);
  g_datalist_clear (&proxy->priv->qdata);
  G_OBJECT_CLASS (group_admin_proxy_parent_class)->finalize (object);
}

static void
group_admin_proxy_get_property (GObject      *object,
  guint         prop_id,
  GValue       *value,
  GParamSpec   *pspec G_GNUC_UNUSED)
{
  const _ExtendedGDBusPropertyInfo *info;
  GVariant *variant;
  g_assert (prop_id != 0 && prop_id - 1 < 1);
  info = _group_admin_property_info_pointers[prop_id - 1];
  variant = g_dbus_proxy_get_cached_property (G_DBUS_PROXY (object), info->parent_struct.name);
  if (info->use_gvariant)
    {
      g_value_set_variant (value, variant);
    }
  else
    {
      if (variant != NULL)
        g_dbus_gvariant_to_gvalue (variant, value);
    }
  if (variant != NULL)
    g_variant_unref (variant);
}

static void
group_admin_proxy_set_property_cb (GDBusProxy *proxy,
  GAsyncResult *res,
  gpointer      user_data)
{
  const _ExtendedGDBusPropertyInfo *info = user_data;
  GError *error;
  GVariant *_ret;
  error = NULL;
  _ret = g_dbus_proxy_call_finish (proxy, res, &error);
  if (!_ret)
    {
      g_warning ("Error setting property '%s' on interface org.group.admin: %s (%s, %d)",
                 info->parent_struct.name, 
                 error->message, g_quark_to_string (error->domain), error->code);
      g_error_free (error);
    }
  else
    {
      g_variant_unref (_ret);
    }
}

static void
group_admin_proxy_set_property (GObject      *object,
  guint         prop_id,
  const GValue *value,
  GParamSpec   *pspec G_GNUC_UNUSED)
{
  const _ExtendedGDBusPropertyInfo *info;
  GVariant *variant;
  g_assert (prop_id != 0 && prop_id - 1 < 1);
  info = _group_admin_property_info_pointers[prop_id - 1];
  variant = g_dbus_gvalue_to_gvariant (value, G_VARIANT_TYPE (info->parent_struct.signature));
  g_dbus_proxy_call (G_DBUS_PROXY (object),
    "org.freedesktop.DBus.Properties.Set",
    g_variant_new ("(ssv)", "org.group.admin", info->parent_struct.name, variant),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    NULL, (GAsyncReadyCallback) group_admin_proxy_set_property_cb, (GDBusPropertyInfo *) &info->parent_struct);
  g_variant_unref (variant);
}

static void
group_admin_proxy_g_signal (GDBusProxy *proxy,
  const gchar *sender_name G_GNUC_UNUSED,
  const gchar *signal_name,
  GVariant *parameters)
{
  _ExtendedGDBusSignalInfo *info;
  GVariantIter iter;
  GVariant *child;
  GValue *paramv;
  gsize num_params;
  gsize n;
  guint signal_id;
  info = (_ExtendedGDBusSignalInfo *) g_dbus_interface_info_lookup_signal ((GDBusInterfaceInfo *) &_group_admin_interface_info.parent_struct, signal_name);
  if (info == NULL)
    return;
  num_params = g_variant_n_children (parameters);
  paramv = g_new0 (GValue, num_params + 1);
  g_value_init (&paramv[0], GROUP_TYPE_ADMIN);
  g_value_set_object (&paramv[0], proxy);
  g_variant_iter_init (&iter, parameters);
  n = 1;
  while ((child = g_variant_iter_next_value (&iter)) != NULL)
    {
      _ExtendedGDBusArgInfo *arg_info = (_ExtendedGDBusArgInfo *) info->parent_struct.args[n - 1];
      if (arg_info->use_gvariant)
        {
          g_value_init (&paramv[n], G_TYPE_VARIANT);
          g_value_set_variant (&paramv[n], child);
          n++;
        }
      else
        g_dbus_gvariant_to_gvalue (child, &paramv[n++]);
      g_variant_unref (child);
    }
  signal_id = g_signal_lookup (info->signal_name, GROUP_TYPE_ADMIN);
  g_signal_emitv (paramv, signal_id, 0, NULL);
  for (n = 0; n < num_params + 1; n++)
    g_value_unset (&paramv[n]);
  g_free (paramv);
}

static void
group_admin_proxy_g_properties_changed (GDBusProxy *_proxy,
  GVariant *changed_properties,
  const gchar *const *invalidated_properties)
{
  groupAdminProxy *proxy = GROUP_ADMIN_PROXY (_proxy);
  guint n;
  const gchar *key;
  GVariantIter *iter;
  _ExtendedGDBusPropertyInfo *info;
  g_variant_get (changed_properties, "a{sv}", &iter);
  while (g_variant_iter_next (iter, "{&sv}", &key, NULL))
    {
      info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_group_admin_interface_info.parent_struct, key);
      g_datalist_remove_data (&proxy->priv->qdata, key);
      if (info != NULL)
        g_object_notify (G_OBJECT (proxy), info->hyphen_name);
    }
  g_variant_iter_free (iter);
  for (n = 0; invalidated_properties[n] != NULL; n++)
    {
      info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_group_admin_interface_info.parent_struct, invalidated_properties[n]);
      g_datalist_remove_data (&proxy->priv->qdata, invalidated_properties[n]);
      if (info != NULL)
        g_object_notify (G_OBJECT (proxy), info->hyphen_name);
    }
}

static const gchar *
group_admin_proxy_get_version (groupAdmin *object)
{
  groupAdminProxy *proxy = GROUP_ADMIN_PROXY (object);
  GVariant *variant;
  const gchar *value = NULL;
  variant = g_dbus_proxy_get_cached_property (G_DBUS_PROXY (proxy), "Version");
  if (variant != NULL)
    {
      value = g_variant_get_string (variant, NULL);
      g_variant_unref (variant);
    }
  return value;
}

static void
group_admin_proxy_init (groupAdminProxy *proxy)
{
#if GLIB_VERSION_MAX_ALLOWED >= GLIB_VERSION_2_38
  proxy->priv = group_admin_proxy_get_instance_private (proxy);
#else
  proxy->priv = G_TYPE_INSTANCE_GET_PRIVATE (proxy, GROUP_TYPE_ADMIN_PROXY, groupAdminProxyPrivate);
#endif

  g_dbus_proxy_set_interface_info (G_DBUS_PROXY (proxy), group_admin_interface_info ());
}

static void
group_admin_proxy_class_init (groupAdminProxyClass *klass)
{
  GObjectClass *gobject_class;
  GDBusProxyClass *proxy_class;

  gobject_class = G_OBJECT_CLASS (klass);
  gobject_class->finalize     = group_admin_proxy_finalize;
  gobject_class->get_property = group_admin_proxy_get_property;
  gobject_class->set_property = group_admin_proxy_set_property;

  proxy_class = G_DBUS_PROXY_CLASS (klass);
  proxy_class->g_signal = group_admin_proxy_g_signal;
  proxy_class->g_properties_changed = group_admin_proxy_g_properties_changed;

  group_admin_override_properties (gobject_class, 1);

#if GLIB_VERSION_MAX_ALLOWED < GLIB_VERSION_2_38
  g_type_class_add_private (klass, sizeof (groupAdminProxyPrivate));
#endif
}

static void
group_admin_proxy_iface_init (groupAdminIface *iface)
{
  iface->get_version = group_admin_proxy_get_version;
}

/**
 * group_admin_proxy_new:
 * @connection: A #GDBusConnection.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: (nullable): A bus name (well-known or unique) or %NULL if @connection is not a message bus connection.
 * @object_path: An object path.
 * @cancellable: (nullable): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously creates a proxy for the D-Bus interface <link linkend="gdbus-interface-org-group-admin.top_of_page">org.group.admin</link>. See g_dbus_proxy_new() for more details.
 *
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call group_admin_proxy_new_finish() to get the result of the operation.
 *
 * See group_admin_proxy_new_sync() for the synchronous, blocking version of this constructor.
 */
void
group_admin_proxy_new (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data)
{
  g_async_initable_new_async (GROUP_TYPE_ADMIN_PROXY, G_PRIORITY_DEFAULT, cancellable, callback, user_data, "g-flags", flags, "g-name", name, "g-connection", connection, "g-object-path", object_path, "g-interface-name", "org.group.admin", NULL);
}

/**
 * group_admin_proxy_new_finish:
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to group_admin_proxy_new().
 * @error: Return location for error or %NULL
 *
 * Finishes an operation started with group_admin_proxy_new().
 *
 * Returns: (transfer full) (type groupAdminProxy): The constructed proxy object or %NULL if @error is set.
 */
groupAdmin *
group_admin_proxy_new_finish (
    GAsyncResult        *res,
    GError             **error)
{
  GObject *ret;
  GObject *source_object;
  source_object = g_async_result_get_source_object (res);
  ret = g_async_initable_new_finish (G_ASYNC_INITABLE (source_object), res, error);
  g_object_unref (source_object);
  if (ret != NULL)
    return GROUP_ADMIN (ret);
  else
    return NULL;
}

/**
 * group_admin_proxy_new_sync:
 * @connection: A #GDBusConnection.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: (nullable): A bus name (well-known or unique) or %NULL if @connection is not a message bus connection.
 * @object_path: An object path.
 * @cancellable: (nullable): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL
 *
 * Synchronously creates a proxy for the D-Bus interface <link linkend="gdbus-interface-org-group-admin.top_of_page">org.group.admin</link>. See g_dbus_proxy_new_sync() for more details.
 *
 * The calling thread is blocked until a reply is received.
 *
 * See group_admin_proxy_new() for the asynchronous version of this constructor.
 *
 * Returns: (transfer full) (type groupAdminProxy): The constructed proxy object or %NULL if @error is set.
 */
groupAdmin *
group_admin_proxy_new_sync (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error)
{
  GInitable *ret;
  ret = g_initable_new (GROUP_TYPE_ADMIN_PROXY, cancellable, error, "g-flags", flags, "g-name", name, "g-connection", connection, "g-object-path", object_path, "g-interface-name", "org.group.admin", NULL);
  if (ret != NULL)
    return GROUP_ADMIN (ret);
  else
    return NULL;
}


/**
 * group_admin_proxy_new_for_bus:
 * @bus_type: A #GBusType.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: A bus name (well-known or unique).
 * @object_path: An object path.
 * @cancellable: (nullable): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied.
 * @user_data: User data to pass to @callback.
 *
 * Like group_admin_proxy_new() but takes a #GBusType instead of a #GDBusConnection.
 *
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call group_admin_proxy_new_for_bus_finish() to get the result of the operation.
 *
 * See group_admin_proxy_new_for_bus_sync() for the synchronous, blocking version of this constructor.
 */
void
group_admin_proxy_new_for_bus (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data)
{
  g_async_initable_new_async (GROUP_TYPE_ADMIN_PROXY, G_PRIORITY_DEFAULT, cancellable, callback, user_data, "g-flags", flags, "g-name", name, "g-bus-type", bus_type, "g-object-path", object_path, "g-interface-name", "org.group.admin", NULL);
}

/**
 * group_admin_proxy_new_for_bus_finish:
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to group_admin_proxy_new_for_bus().
 * @error: Return location for error or %NULL
 *
 * Finishes an operation started with group_admin_proxy_new_for_bus().
 *
 * Returns: (transfer full) (type groupAdminProxy): The constructed proxy object or %NULL if @error is set.
 */
groupAdmin *
group_admin_proxy_new_for_bus_finish (
    GAsyncResult        *res,
    GError             **error)
{
  GObject *ret;
  GObject *source_object;
  source_object = g_async_result_get_source_object (res);
  ret = g_async_initable_new_finish (G_ASYNC_INITABLE (source_object), res, error);
  g_object_unref (source_object);
  if (ret != NULL)
    return GROUP_ADMIN (ret);
  else
    return NULL;
}

/**
 * group_admin_proxy_new_for_bus_sync:
 * @bus_type: A #GBusType.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: A bus name (well-known or unique).
 * @object_path: An object path.
 * @cancellable: (nullable): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL
 *
 * Like group_admin_proxy_new_sync() but takes a #GBusType instead of a #GDBusConnection.
 *
 * The calling thread is blocked until a reply is received.
 *
 * See group_admin_proxy_new_for_bus() for the asynchronous version of this constructor.
 *
 * Returns: (transfer full) (type groupAdminProxy): The constructed proxy object or %NULL if @error is set.
 */
groupAdmin *
group_admin_proxy_new_for_bus_sync (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error)
{
  GInitable *ret;
  ret = g_initable_new (GROUP_TYPE_ADMIN_PROXY, cancellable, error, "g-flags", flags, "g-name", name, "g-bus-type", bus_type, "g-object-path", object_path, "g-interface-name", "org.group.admin", NULL);
  if (ret != NULL)
    return GROUP_ADMIN (ret);
  else
    return NULL;
}


/* ------------------------------------------------------------------------ */

/**
 * groupAdminSkeleton:
 *
 * The #groupAdminSkeleton structure contains only private data and should only be accessed using the provided API.
 */

/**
 * groupAdminSkeletonClass:
 * @parent_class: The parent class.
 *
 * Class structure for #groupAdminSkeleton.
 */

struct _groupAdminSkeletonPrivate
{
  GValue *properties;
  GList *changed_properties;
  GSource *changed_properties_idle_source;
  GMainContext *context;
  GMutex lock;
};

static void
_group_admin_skeleton_handle_method_call (
  GDBusConnection *connection G_GNUC_UNUSED,
  const gchar *sender G_GNUC_UNUSED,
  const gchar *object_path G_GNUC_UNUSED,
  const gchar *interface_name,
  const gchar *method_name,
  GVariant *parameters,
  GDBusMethodInvocation *invocation,
  gpointer user_data)
{
  groupAdminSkeleton *skeleton = GROUP_ADMIN_SKELETON (user_data);
  _ExtendedGDBusMethodInfo *info;
  GVariantIter iter;
  GVariant *child;
  GValue *paramv;
  gsize num_params;
  guint num_extra;
  gsize n;
  guint signal_id;
  GValue return_value = G_VALUE_INIT;
  info = (_ExtendedGDBusMethodInfo *) g_dbus_method_invocation_get_method_info (invocation);
  g_assert (info != NULL);
  num_params = g_variant_n_children (parameters);
  num_extra = info->pass_fdlist ? 3 : 2;  paramv = g_new0 (GValue, num_params + num_extra);
  n = 0;
  g_value_init (&paramv[n], GROUP_TYPE_ADMIN);
  g_value_set_object (&paramv[n++], skeleton);
  g_value_init (&paramv[n], G_TYPE_DBUS_METHOD_INVOCATION);
  g_value_set_object (&paramv[n++], invocation);
  if (info->pass_fdlist)
    {
#ifdef G_OS_UNIX
      g_value_init (&paramv[n], G_TYPE_UNIX_FD_LIST);
      g_value_set_object (&paramv[n++], g_dbus_message_get_unix_fd_list (g_dbus_method_invocation_get_message (invocation)));
#else
      g_assert_not_reached ();
#endif
    }
  g_variant_iter_init (&iter, parameters);
  while ((child = g_variant_iter_next_value (&iter)) != NULL)
    {
      _ExtendedGDBusArgInfo *arg_info = (_ExtendedGDBusArgInfo *) info->parent_struct.in_args[n - num_extra];
      if (arg_info->use_gvariant)
        {
          g_value_init (&paramv[n], G_TYPE_VARIANT);
          g_value_set_variant (&paramv[n], child);
          n++;
        }
      else
        g_dbus_gvariant_to_gvalue (child, &paramv[n++]);
      g_variant_unref (child);
    }
  signal_id = g_signal_lookup (info->signal_name, GROUP_TYPE_ADMIN);
  g_value_init (&return_value, G_TYPE_BOOLEAN);
  g_signal_emitv (paramv, signal_id, 0, &return_value);
  if (!g_value_get_boolean (&return_value))
    g_dbus_method_invocation_return_error (invocation, G_DBUS_ERROR, G_DBUS_ERROR_UNKNOWN_METHOD, "Method %s is not implemented on interface %s", method_name, interface_name);
  g_value_unset (&return_value);
  for (n = 0; n < num_params + num_extra; n++)
    g_value_unset (&paramv[n]);
  g_free (paramv);
}

static GVariant *
_group_admin_skeleton_handle_get_property (
  GDBusConnection *connection G_GNUC_UNUSED,
  const gchar *sender G_GNUC_UNUSED,
  const gchar *object_path G_GNUC_UNUSED,
  const gchar *interface_name G_GNUC_UNUSED,
  const gchar *property_name,
  GError **error,
  gpointer user_data)
{
  groupAdminSkeleton *skeleton = GROUP_ADMIN_SKELETON (user_data);
  GValue value = G_VALUE_INIT;
  GParamSpec *pspec;
  _ExtendedGDBusPropertyInfo *info;
  GVariant *ret;
  ret = NULL;
  info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_group_admin_interface_info.parent_struct, property_name);
  g_assert (info != NULL);
  pspec = g_object_class_find_property (G_OBJECT_GET_CLASS (skeleton), info->hyphen_name);
  if (pspec == NULL)
    {
      g_set_error (error, G_DBUS_ERROR, G_DBUS_ERROR_INVALID_ARGS, "No property with name %s", property_name);
    }
  else
    {
      g_value_init (&value, pspec->value_type);
      g_object_get_property (G_OBJECT (skeleton), info->hyphen_name, &value);
      ret = g_dbus_gvalue_to_gvariant (&value, G_VARIANT_TYPE (info->parent_struct.signature));
      g_value_unset (&value);
    }
  return ret;
}

static gboolean
_group_admin_skeleton_handle_set_property (
  GDBusConnection *connection G_GNUC_UNUSED,
  const gchar *sender G_GNUC_UNUSED,
  const gchar *object_path G_GNUC_UNUSED,
  const gchar *interface_name G_GNUC_UNUSED,
  const gchar *property_name,
  GVariant *variant,
  GError **error,
  gpointer user_data)
{
  groupAdminSkeleton *skeleton = GROUP_ADMIN_SKELETON (user_data);
  GValue value = G_VALUE_INIT;
  GParamSpec *pspec;
  _ExtendedGDBusPropertyInfo *info;
  gboolean ret;
  ret = FALSE;
  info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_group_admin_interface_info.parent_struct, property_name);
  g_assert (info != NULL);
  pspec = g_object_class_find_property (G_OBJECT_GET_CLASS (skeleton), info->hyphen_name);
  if (pspec == NULL)
    {
      g_set_error (error, G_DBUS_ERROR, G_DBUS_ERROR_INVALID_ARGS, "No property with name %s", property_name);
    }
  else
    {
      if (info->use_gvariant)
        g_value_set_variant (&value, variant);
      else
        g_dbus_gvariant_to_gvalue (variant, &value);
      g_object_set_property (G_OBJECT (skeleton), info->hyphen_name, &value);
      g_value_unset (&value);
      ret = TRUE;
    }
  return ret;
}

static const GDBusInterfaceVTable _group_admin_skeleton_vtable =
{
  _group_admin_skeleton_handle_method_call,
  _group_admin_skeleton_handle_get_property,
  _group_admin_skeleton_handle_set_property,
  {NULL}
};

static GDBusInterfaceInfo *
group_admin_skeleton_dbus_interface_get_info (GDBusInterfaceSkeleton *skeleton G_GNUC_UNUSED)
{
  return group_admin_interface_info ();
}

static GDBusInterfaceVTable *
group_admin_skeleton_dbus_interface_get_vtable (GDBusInterfaceSkeleton *skeleton G_GNUC_UNUSED)
{
  return (GDBusInterfaceVTable *) &_group_admin_skeleton_vtable;
}

static GVariant *
group_admin_skeleton_dbus_interface_get_properties (GDBusInterfaceSkeleton *_skeleton)
{
  groupAdminSkeleton *skeleton = GROUP_ADMIN_SKELETON (_skeleton);

  GVariantBuilder builder;
  guint n;
  g_variant_builder_init (&builder, G_VARIANT_TYPE ("a{sv}"));
  if (_group_admin_interface_info.parent_struct.properties == NULL)
    goto out;
  for (n = 0; _group_admin_interface_info.parent_struct.properties[n] != NULL; n++)
    {
      GDBusPropertyInfo *info = _group_admin_interface_info.parent_struct.properties[n];
      if (info->flags & G_DBUS_PROPERTY_INFO_FLAGS_READABLE)
        {
          GVariant *value;
          value = _group_admin_skeleton_handle_get_property (g_dbus_interface_skeleton_get_connection (G_DBUS_INTERFACE_SKELETON (skeleton)), NULL, g_dbus_interface_skeleton_get_object_path (G_DBUS_INTERFACE_SKELETON (skeleton)), "org.group.admin", info->name, NULL, skeleton);
          if (value != NULL)
            {
              g_variant_take_ref (value);
              g_variant_builder_add (&builder, "{sv}", info->name, value);
              g_variant_unref (value);
            }
        }
    }
out:
  return g_variant_builder_end (&builder);
}

static gboolean _group_admin_emit_changed (gpointer user_data);

static void
group_admin_skeleton_dbus_interface_flush (GDBusInterfaceSkeleton *_skeleton)
{
  groupAdminSkeleton *skeleton = GROUP_ADMIN_SKELETON (_skeleton);
  gboolean emit_changed = FALSE;

  g_mutex_lock (&skeleton->priv->lock);
  if (skeleton->priv->changed_properties_idle_source != NULL)
    {
      g_source_destroy (skeleton->priv->changed_properties_idle_source);
      skeleton->priv->changed_properties_idle_source = NULL;
      emit_changed = TRUE;
    }
  g_mutex_unlock (&skeleton->priv->lock);

  if (emit_changed)
    _group_admin_emit_changed (skeleton);
}

static void
_group_admin_on_signal_group_added (
    groupAdmin *object,
    const gchar *arg_user)
{
  groupAdminSkeleton *skeleton = GROUP_ADMIN_SKELETON (object);

  GList      *connections, *l;
  GVariant   *signal_variant;
  connections = g_dbus_interface_skeleton_get_connections (G_DBUS_INTERFACE_SKELETON (skeleton));

  signal_variant = g_variant_ref_sink (g_variant_new ("(o)",
                   arg_user));
  for (l = connections; l != NULL; l = l->next)
    {
      GDBusConnection *connection = l->data;
      g_dbus_connection_emit_signal (connection,
        NULL, g_dbus_interface_skeleton_get_object_path (G_DBUS_INTERFACE_SKELETON (skeleton)), "org.group.admin", "GroupAdded",
        signal_variant, NULL);
    }
  g_variant_unref (signal_variant);
  g_list_free_full (connections, g_object_unref);
}

static void
_group_admin_on_signal_group_deleted (
    groupAdmin *object,
    const gchar *arg_user)
{
  groupAdminSkeleton *skeleton = GROUP_ADMIN_SKELETON (object);

  GList      *connections, *l;
  GVariant   *signal_variant;
  connections = g_dbus_interface_skeleton_get_connections (G_DBUS_INTERFACE_SKELETON (skeleton));

  signal_variant = g_variant_ref_sink (g_variant_new ("(o)",
                   arg_user));
  for (l = connections; l != NULL; l = l->next)
    {
      GDBusConnection *connection = l->data;
      g_dbus_connection_emit_signal (connection,
        NULL, g_dbus_interface_skeleton_get_object_path (G_DBUS_INTERFACE_SKELETON (skeleton)), "org.group.admin", "GroupDeleted",
        signal_variant, NULL);
    }
  g_variant_unref (signal_variant);
  g_list_free_full (connections, g_object_unref);
}

static void group_admin_skeleton_iface_init (groupAdminIface *iface);
#if GLIB_VERSION_MAX_ALLOWED >= GLIB_VERSION_2_38
G_DEFINE_TYPE_WITH_CODE (groupAdminSkeleton, group_admin_skeleton, G_TYPE_DBUS_INTERFACE_SKELETON,
                         G_ADD_PRIVATE (groupAdminSkeleton)
                         G_IMPLEMENT_INTERFACE (GROUP_TYPE_ADMIN, group_admin_skeleton_iface_init))

#else
G_DEFINE_TYPE_WITH_CODE (groupAdminSkeleton, group_admin_skeleton, G_TYPE_DBUS_INTERFACE_SKELETON,
                         G_IMPLEMENT_INTERFACE (GROUP_TYPE_ADMIN, group_admin_skeleton_iface_init))

#endif
static void
group_admin_skeleton_finalize (GObject *object)
{
  groupAdminSkeleton *skeleton = GROUP_ADMIN_SKELETON (object);
  guint n;
  for (n = 0; n < 1; n++)
    g_value_unset (&skeleton->priv->properties[n]);
  g_free (skeleton->priv->properties);
  g_list_free_full (skeleton->priv->changed_properties, (GDestroyNotify) _changed_property_free);
  if (skeleton->priv->changed_properties_idle_source != NULL)
    g_source_destroy (skeleton->priv->changed_properties_idle_source);
  g_main_context_unref (skeleton->priv->context);
  g_mutex_clear (&skeleton->priv->lock);
  G_OBJECT_CLASS (group_admin_skeleton_parent_class)->finalize (object);
}

static void
group_admin_skeleton_get_property (GObject      *object,
  guint         prop_id,
  GValue       *value,
  GParamSpec   *pspec G_GNUC_UNUSED)
{
  groupAdminSkeleton *skeleton = GROUP_ADMIN_SKELETON (object);
  g_assert (prop_id != 0 && prop_id - 1 < 1);
  g_mutex_lock (&skeleton->priv->lock);
  g_value_copy (&skeleton->priv->properties[prop_id - 1], value);
  g_mutex_unlock (&skeleton->priv->lock);
}

static gboolean
_group_admin_emit_changed (gpointer user_data)
{
  groupAdminSkeleton *skeleton = GROUP_ADMIN_SKELETON (user_data);
  GList *l;
  GVariantBuilder builder;
  GVariantBuilder invalidated_builder;
  guint num_changes;

  g_mutex_lock (&skeleton->priv->lock);
  g_variant_builder_init (&builder, G_VARIANT_TYPE ("a{sv}"));
  g_variant_builder_init (&invalidated_builder, G_VARIANT_TYPE ("as"));
  for (l = skeleton->priv->changed_properties, num_changes = 0; l != NULL; l = l->next)
    {
      ChangedProperty *cp = l->data;
      GVariant *variant;
      const GValue *cur_value;

      cur_value = &skeleton->priv->properties[cp->prop_id - 1];
      if (!_g_value_equal (cur_value, &cp->orig_value))
        {
          variant = g_dbus_gvalue_to_gvariant (cur_value, G_VARIANT_TYPE (cp->info->parent_struct.signature));
          g_variant_builder_add (&builder, "{sv}", cp->info->parent_struct.name, variant);
          g_variant_unref (variant);
          num_changes++;
        }
    }
  if (num_changes > 0)
    {
      GList *connections, *ll;
      GVariant *signal_variant;
      signal_variant = g_variant_ref_sink (g_variant_new ("(sa{sv}as)", "org.group.admin",
                                           &builder, &invalidated_builder));
      connections = g_dbus_interface_skeleton_get_connections (G_DBUS_INTERFACE_SKELETON (skeleton));
      for (ll = connections; ll != NULL; ll = ll->next)
        {
          GDBusConnection *connection = ll->data;

          g_dbus_connection_emit_signal (connection,
                                         NULL, g_dbus_interface_skeleton_get_object_path (G_DBUS_INTERFACE_SKELETON (skeleton)),
                                         "org.freedesktop.DBus.Properties",
                                         "PropertiesChanged",
                                         signal_variant,
                                         NULL);
        }
      g_variant_unref (signal_variant);
      g_list_free_full (connections, g_object_unref);
    }
  else
    {
      g_variant_builder_clear (&builder);
      g_variant_builder_clear (&invalidated_builder);
    }
  g_list_free_full (skeleton->priv->changed_properties, (GDestroyNotify) _changed_property_free);
  skeleton->priv->changed_properties = NULL;
  skeleton->priv->changed_properties_idle_source = NULL;
  g_mutex_unlock (&skeleton->priv->lock);
  return FALSE;
}

static void
_group_admin_schedule_emit_changed (groupAdminSkeleton *skeleton, const _ExtendedGDBusPropertyInfo *info, guint prop_id, const GValue *orig_value)
{
  ChangedProperty *cp;
  GList *l;
  cp = NULL;
  for (l = skeleton->priv->changed_properties; l != NULL; l = l->next)
    {
      ChangedProperty *i_cp = l->data;
      if (i_cp->info == info)
        {
          cp = i_cp;
          break;
        }
    }
  if (cp == NULL)
    {
      cp = g_new0 (ChangedProperty, 1);
      cp->prop_id = prop_id;
      cp->info = info;
      skeleton->priv->changed_properties = g_list_prepend (skeleton->priv->changed_properties, cp);
      g_value_init (&cp->orig_value, G_VALUE_TYPE (orig_value));
      g_value_copy (orig_value, &cp->orig_value);
    }
}

static void
group_admin_skeleton_notify (GObject      *object,
  GParamSpec *pspec G_GNUC_UNUSED)
{
  groupAdminSkeleton *skeleton = GROUP_ADMIN_SKELETON (object);
  g_mutex_lock (&skeleton->priv->lock);
  if (skeleton->priv->changed_properties != NULL &&
      skeleton->priv->changed_properties_idle_source == NULL)
    {
      skeleton->priv->changed_properties_idle_source = g_idle_source_new ();
      g_source_set_priority (skeleton->priv->changed_properties_idle_source, G_PRIORITY_DEFAULT);
      g_source_set_callback (skeleton->priv->changed_properties_idle_source, _group_admin_emit_changed, g_object_ref (skeleton), (GDestroyNotify) g_object_unref);
      g_source_set_name (skeleton->priv->changed_properties_idle_source, "[generated] _group_admin_emit_changed");
      g_source_attach (skeleton->priv->changed_properties_idle_source, skeleton->priv->context);
      g_source_unref (skeleton->priv->changed_properties_idle_source);
    }
  g_mutex_unlock (&skeleton->priv->lock);
}

static void
group_admin_skeleton_set_property (GObject      *object,
  guint         prop_id,
  const GValue *value,
  GParamSpec   *pspec)
{
  groupAdminSkeleton *skeleton = GROUP_ADMIN_SKELETON (object);
  g_assert (prop_id != 0 && prop_id - 1 < 1);
  g_mutex_lock (&skeleton->priv->lock);
  g_object_freeze_notify (object);
  if (!_g_value_equal (value, &skeleton->priv->properties[prop_id - 1]))
    {
      if (g_dbus_interface_skeleton_get_connection (G_DBUS_INTERFACE_SKELETON (skeleton)) != NULL)
        _group_admin_schedule_emit_changed (skeleton, _group_admin_property_info_pointers[prop_id - 1], prop_id, &skeleton->priv->properties[prop_id - 1]);
      g_value_copy (value, &skeleton->priv->properties[prop_id - 1]);
      g_object_notify_by_pspec (object, pspec);
    }
  g_mutex_unlock (&skeleton->priv->lock);
  g_object_thaw_notify (object);
}

static void
group_admin_skeleton_init (groupAdminSkeleton *skeleton)
{
#if GLIB_VERSION_MAX_ALLOWED >= GLIB_VERSION_2_38
  skeleton->priv = group_admin_skeleton_get_instance_private (skeleton);
#else
  skeleton->priv = G_TYPE_INSTANCE_GET_PRIVATE (skeleton, GROUP_TYPE_ADMIN_SKELETON, groupAdminSkeletonPrivate);
#endif

  g_mutex_init (&skeleton->priv->lock);
  skeleton->priv->context = g_main_context_ref_thread_default ();
  skeleton->priv->properties = g_new0 (GValue, 1);
  g_value_init (&skeleton->priv->properties[0], G_TYPE_STRING);
}

static const gchar *
group_admin_skeleton_get_version (groupAdmin *object)
{
  groupAdminSkeleton *skeleton = GROUP_ADMIN_SKELETON (object);
  const gchar *value;
  g_mutex_lock (&skeleton->priv->lock);
  value = g_value_get_string (&(skeleton->priv->properties[0]));
  g_mutex_unlock (&skeleton->priv->lock);
  return value;
}

static void
group_admin_skeleton_class_init (groupAdminSkeletonClass *klass)
{
  GObjectClass *gobject_class;
  GDBusInterfaceSkeletonClass *skeleton_class;

  gobject_class = G_OBJECT_CLASS (klass);
  gobject_class->finalize = group_admin_skeleton_finalize;
  gobject_class->get_property = group_admin_skeleton_get_property;
  gobject_class->set_property = group_admin_skeleton_set_property;
  gobject_class->notify       = group_admin_skeleton_notify;


  group_admin_override_properties (gobject_class, 1);

  skeleton_class = G_DBUS_INTERFACE_SKELETON_CLASS (klass);
  skeleton_class->get_info = group_admin_skeleton_dbus_interface_get_info;
  skeleton_class->get_properties = group_admin_skeleton_dbus_interface_get_properties;
  skeleton_class->flush = group_admin_skeleton_dbus_interface_flush;
  skeleton_class->get_vtable = group_admin_skeleton_dbus_interface_get_vtable;

#if GLIB_VERSION_MAX_ALLOWED < GLIB_VERSION_2_38
  g_type_class_add_private (klass, sizeof (groupAdminSkeletonPrivate));
#endif
}

static void
group_admin_skeleton_iface_init (groupAdminIface *iface)
{
  iface->group_added = _group_admin_on_signal_group_added;
  iface->group_deleted = _group_admin_on_signal_group_deleted;
  iface->get_version = group_admin_skeleton_get_version;
}

/**
 * group_admin_skeleton_new:
 *
 * Creates a skeleton object for the D-Bus interface <link linkend="gdbus-interface-org-group-admin.top_of_page">org.group.admin</link>.
 *
 * Returns: (transfer full) (type groupAdminSkeleton): The skeleton object.
 */
groupAdmin *
group_admin_skeleton_new (void)
{
  return GROUP_ADMIN (g_object_new (GROUP_TYPE_ADMIN_SKELETON, NULL));
}

